### ISSUE TITLE
Missing text for default gear. ?WeaponName?, ?ProtectorName?, and ?AccessoryName?

### ISSUE THREAD

**Issue by Blanket-Fluff** [CornflakeWoof/Diablo-Style-Loot-for-Elden-Ring#2]
Program versions
DSL Beta 4
DSMapStudio 1.06
ModEngine 2 preview4
Elden Ring v1.08.1

Following the How To Use step by step, I was able to generate a new seed which works fine except that the non-randomized gear is missing its respective name and info. This means any weapons, ammo, armour, and talismans that are guaranteed drops, or sold by vendors. They still function as they do normally, it's just that their names and descriptions are missing and show up as variants of ?WeaponName?, ?WeaponInfo?, ?AccessoryCaption? etc. All other Diablo Style Loot is working fine and has appropriate names and custom lore.
Screenshots: [https://imgur.com/a/6nJhRNN](https://imgur.com/a/6nJhRNN)

I don't know where in the process the default text could have been lost, as this is the first time I use these tools. It is certainly possible this has happened due to a mistake on my part, and I would be happy of any assistance in sorting this out. 

If we assume everything was done properly on my end and this still occurred, could this have been an issue with any of the provided files or directions? 

I am attaching a zip file containing the generated diabloloot_er folder. 
[diabloloot_er.zip](https://github.com/CornflakeWoof/Diablo-Style-Loot-for-Elden-Ring/files/10453061/diabloloot_er.zip)

**Comment by CornflakeWoof** [comment]
AH! Sorry about that, I know exactly what's up, you've done everything correctly - so since Beta 0.4 DSL only generates its own text entries, it doesn't integrate them into a copy of the vanilla text entries anymore - this was to ensure compatibility when integrating with other mods. Downside is, DSMapStudio replaces all text entries with just the ones provided by DSL, so we end up losing

What I hadn't updated on here was that the new tool to use is DSMSPortable ( https://github.com/mountlover/DSMSPortable/releases/tag/v1.4.7 ), using the --fmgmerge function in this program allows us to integrate text entries without needing to include the entire vanilla item text as well.

Download DSMSPortable, unzip the attached .bat file into its folder, edit the path variables at the top to match yours (no quotes or closing "/"s!) and give it a try - make sure to run the bat in a command window (cmd) to see where things have gone wrong if they do!

[ImportIntoDiabloLootER_release.zip](https://github.com/CornflakeWoof/Diablo-Style-Loot-for-Elden-Ring/files/10529609/ImportIntoDiabloLootER_release.zip)

I've updated the mod's description on here to reflect this. Sorry for the delay!
