### ISSUE TITLE
Effect of some armor and talismans not accurately described

### ISSUE THREAD

**Issue by nullspeaker** [CornflakeWoof/Diablo-Style-Loot-for-Elden-Ring#3]
![image](https://user-images.githubusercontent.com/2228057/215289278-685ebe1d-208d-4151-b6d1-f76f26e5adb3.png)
^ on "Gravity sorceries +30%". Seems to be the same with similar effects for other types.

![image](https://user-images.githubusercontent.com/2228057/215289304-382e869f-e40f-4a1f-8b4f-be9bfcdf1623.png)
Additionally, this seems to do nothing for sorcery scaling. Damage does not change, but FP consumption does. (Perhaps this effect only works on catalysts?)

Also, tooltips like this:
![image](https://user-images.githubusercontent.com/2228057/215289362-56f8a92a-04ea-4566-bd97-53124d06a507.png)
while it provides accurate information, are a little confusing. Initially I thought it was (original + original*1.05) for a total of 205% the original damage, but it's just an extra 5%. Perhaps this could be generated as "+5% xyz dealt, 7% xyz taken"? Not sure if that's something you can control.

I'm also using ERR. Mod load order:
```toml
mods = [
	{ enabled = true, name = "ERRDSL", path = "errdsl" },
	{ enabled = true, name = "DSL", path = "diabloloot_er" },
	{ enabled = true, name = "ERR", path = "err" },
	{ enabled = true, name = "mods", path = "mod" }
]
```

**Comment by CornflakeWoof** [comment]
Thanks for raising this!

I'll be taking the Lusat and Azur effects out for Beta 0.5, they just don't seem to work unless they're on a catalyst.

Regarding the second part - that kind of awkwardly presented information is a side effect of how I'd set up that particular SpEffect to generate and how DSL handles creating the descriptions, I'll be hand-making the possible SpEffects for DSL Remastered so this shouldn't be an issue in the rewritten DSL - as I'll be focusing on that going forward, Beta 0.5 will unfortunately retain that awkwardness for now!

That also highlights a nastier bug that should be fixed in Beta 0.5, where multi-effect loot kept getting its earlier effects overwritten by the later ones - that bit of loot was probably supposed to have different effects, not the same one twice! This will also be fixed in Beta 0.5
